name: "Terraform Destroy"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  destroy-resources:
    name: "Destroy Resources"
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/terraform-destroy-aws.yml@main
    secrets: inherit
